# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: King Midas Clique
email: info@midasclique.com
description: > # this means to ignore newlines until "baseurl:"
  TODO: King Midas Clique Site Description to appear in document head meta for 
  Google search results
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://midasclique.com" # the base hostname & protocol for your site
twitter_username: kingmidasclique
facebook_page: "King-Midas-Clique-951015468325303"

# Build settings
markdown: kramdown

collections:
  tracks:
    output: true
    permalink: /track/:slug/
  albums:
    output: true
    permalink: /album/:slug/
